version: '3.3'

services:
  rpistat_integration:
    container_name: rpistat_integration
    build:
      context: .
      dockerfile: test.integration.Dockerfile
    environment:
      DEPLOY_ENV: "int"
    depends_on:
      - rpistat
      - rpistat_smocker_ipify
    volumes:
      - ./target/binutil/dockerize:/usr/bin/dockerize
      - ./target/report/:/workspace/target/report/

  rpistat:
    image: tecnickcom/rpistat:latest
    container_name: rpistat
    restart: always
    env_file:
      - target/rpistat.integration.env
    entrypoint: [
        "/usr/bin/dockerize",
        "-wait", "tcp://rpistat_smocker_ipify:8081",
        "/usr/bin/rpistat"
    ]
    volumes:
      - ./target/binutil/dockerize:/usr/bin/dockerize

  rpistat_smocker_ipify:
    container_name: rpistat_smocker_ipify
    image: thiht/smocker
