openapi: 3.0.3
info:
  title: rpistat
  description: Public API
  contact:
    email: info@tecnick.com
  license:
    name: Internal use only. All rights reserved.
    url: https://github.com/tecnickcom/rpistat/blob/main/LICENSE
  version: 2.0.0
servers:
  - url: https://rpistat:65501/
tags:
  - name: ping
    description: Ping this service
  - name: stats
    description: Returns system usage statistics
paths:
  /ping:
    get:
      tags:
        - ping
      summary: Check if the service is reachable
      responses:
        '200':
          description: The service is reachable
          content:
            text/plain:
              schema:
                type: string
                description: OK
  /stats:
    get:
      tags:
        - stats
      summary: Returns system usage statistics
      responses:
        '200':
          description: System usage statistics
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/stats'
components:
  schemas:
    stats:
      type: object
      properties:
        datetime:
          type: string
          description: >-
            DateTime is the human-readable date and time when the response is
            sent.
        timestamp:
          type: integer
          description: >-
            Timestamp is the machine-readable UTC timestamp in nanoseconds since
            EPOCH.
        hostname:
          type: string
          description: Hostname name of the host.
        uptime:
          type: integer
          description: Uptime time since last system boot.
        memory_total:
          type: integer
          description: Total Memory in bytes.
        memory_free:
          type: integer
          description: Total free memory in bytes.
        memory_used:
          type: integer
          description: Total memory used in bytes.
        memory_usage:
          type: number
          description: Total memory used in percentage
        load_1m:
          type: number
          description: Load is the 1 minute load average.
        load_5m:
          type: number
          description: Load is the 5 minute load average.
        load_15m:
          type: number
          description: Load is the 15 minute load average.
        temperature_cpu:
          type: number
          description: CPU Temperature in Celsius Degrees.
        disk_total:
          type: integer
          description: Total Disk size in bytes.
        disk_free:
          type: integer
          description: Total free disk space in bytes.
        disk_used:
          type: integer
          description: Total disk used in bytes.
        disk_usage:
          type: number
          description: Total disk used in percentage
        network:
          type: array
          items:
            type: object
            description: >-
              Network contains an array of network statistics, one entry for
              each physical interface.
            properties:
              nic:
                type: string
                description: NIC name.
              rx:
                type: integer
                description: Received bytes.
              tx:
                type: integer
                description: Transmitted bytes.
