---
# yamllint disable rule:line-length
project:
  name: rpistat
  title: rpistat
  category: Application
  copyright_start_year: "2022"
  copyright_owner: Nicola Asuni - Tecnick.com LTD
  license_url: https://github.com/tecnickcom/rpistat/blob/main/LICENSE
  cvs: https://github.com/tecnickcom/rpistat
  tagline: Web-Service to collext Raspberry PI 4 system usage statistics
  logo: doc/images/logo.png
team:
  name:
  title:
  info:
  slack:
  escalation:
attachments:
doclinks:
  public:
    general:
      name: General
      description: General project documentation
      links:
        github:
          name: GitHup project page
          url: https://github.com/tecnickcom/rpistat
slack:
dependencies:
environment:
